### ISSUE TITLE
Buttons: `zeroFootSensors` seems to be never used

### ISSUE THREAD

**Issue by jaagut** [bit-bots/bitbots_lowlevel#137]
In bitbots_buttons, the function `zeroFootSensors` seems to be never used.

## Expected behavior
To make the intended functionality work, I would expect, that it is necessary to call the function at one point.

**Comment by timonegk** [comment]
Yes it is currently not used because we are not allowed to do it in the game. But we wanted to keep the function if we want to use different modes depending on the in_game variable (#138).
