### ISSUE TITLE
bitbots_ros_controll: bitbots_ros_control_params.cfg has no parameters

### ISSUE THREAD

**Issue by JanGut** [bit-bots/bitbots_lowlevel#26]
The `bitbots_ros_control_params.cfg` dynamic reconfigure file has no parameters. Is this file still needed?

**Comment by SammyRamone** [comment]
during refactoring, the parameters were one after the other removed or moved into the servo file

**Comment by jgueldenstein** [comment]
It can be deleted in my opinion
