### ISSUE TITLE
bitbots_ros_controll: Subscription of /ros_control/set_torque

### ISSUE THREAD

**Issue by JanGut** [bit-bots/bitbots_lowlevel#27]
The `bitbots_ros_controll` node subscribes to `/ros_control/set_torque` but this message has no publisher. Is this subscriber still needed?

Differentiate between `/ros_control/set_torque` and `/ros_control/set_torque_individual`.

**Comment by jgueldenstein** [comment]
Yes. set_torque is used manually, set_torque_individual is used by the record ui and also manually for example when you want to move the head manually for testing the vision

**Comment by JanGut** [comment]
Okay, thanks for the description!
