### ISSUE TITLE
bitbots_dynamixel_debug is not working after DynamixelSDK update

### ISSUE THREAD

**Issue by timonegk** [bit-bots/bitbots_lowlevel#28]

**Comment by SammyRamone** [comment]
should just be replaced by http://wiki.ros.org/dynamixel_controllers/Tutorials/SettingUpDynamixel

**Comment by SammyRamone** [comment]
> should just be replaced by http://wiki.ros.org/dynamixel_controllers/Tutorials/SettingUpDynamixel

never mind, this GUI is only for protocol 1
