### ISSUE TITLE
ros control: weird Segfault

### ISSUE THREAD

**Issue by SammyRamone** [bit-bots/bitbots_lowlevel#33]
On Jack ros_control fails with segfault when the robot is moving and having package reading errors for some time
It is always a memory problem but it happens at various places
RAM was changed to make sure that it is not the problem source
Maybe this is an issue with the new version of the DynamixelSDK or due to the refactoring of ros_control. Needs to be tested with older versions of the software to see what is responsible

**Comment by NFiedler** [comment]
Also, we have to figure out whether this is an error due to the specific robot or because of the massive  
and frequent errors on the bus.

**Comment by NFiedler** [comment]
I reproduced this error on Donna.
